app = "cronwatch"
primary_region = "cdg"

[build]
  dockerfile = "infra/docker/prod/Dockerfile"

[env]
  APP_ENV = "production"
  APP_DEBUG = "0"
  DB_CONNECTION = "pgsql"
  DB_HOST = "pgbouncer.1zvn90k4qe1rkpew.flympg.net"
  DB_PORT = "5432"
  DB_DATABASE = "fly-db"
  DB_USERNAME = "fly-user"
  LOG_CHANNEL = "stack"
  LOG_STACK = "stderr,betterstack"
  LOG_LEVEL = "info"
  BETTERSTACK_ENDPOINT = "tls://s1674307.eu-nbg-2.betterstackdata.com:443?token=dyChFCe9eTSbjuScry8VqRYB"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[deploy]
  release_command = "php /var/www/html/artisan migrate --force"

[[vm]]
  memory = "1024mb"
  cpu_kind = "shared"
  cpus = 1
