version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: infra/docker/prod/Dockerfile
    image: cronwatch:latest
    container_name: cronwatch_app
    ports:
      - "8080:8080"
    environment:
      APP_ENV: local
      APP_DEBUG: 1
      APP_KEY: base64:YOUR_APP_KEY
      DB_CONNECTION: pgsql
      DB_HOST: your_pg_host
      DB_PORT: 5432
      DB_DATABASE: your_db_name
      DB_USERNAME: your_db_user
      DB_PASSWORD: your_db_pass
    volumes:
      - ./apps/backend:/var/www/html
      - ./storage:/var/www/html/storage
